#$L$
# Copyright (C) 2016 Ridgerun (http://www.ridgerun.com).
##$L$


FETCHER_NO_DOWNLOAD=yes
GSTREAMER_VERSION=gstreamer-1.0

include ../../bsp/classes/rrsdk.class
include $(CLASSES)/gstreamer-plugin.class
